FROM node:16.14.0-slim

WORKDIR /app

COPY ./package*.json ./
COPY ./yarn.lock ./


RUN yarn

COPY ./ ./

ARG LOCAL_IP
ARG SKARTNER_WEB_APP_ENV
ENV NEXT_PUBLIC_LOCAL_IP=${LOCAL_IP:?error}
ENV NEXT_PUBLIC_APP_ENV=${SKARTNER_WEB_APP_ENV:?error}

CMD ["yarn", "dev"]
