query greWords($where: GreWordWhereInput, $skip: Int, $take: Int) {
  greWords(where: $where, skip: $skip, take: $take) {
    id
    spelling
    gptPrompts {
      id
      input
      response
    }
  }
  greWordsCount(where: $where)
}
