query greWords($where: GreWordWhereInput, $skip: Int, $take: Int) {
  greWords(where: $where, skip: $skip, take: $take) {
    id
    spelling
    gptPrompts {
      id
      input
      response
      editedResponse
      greWordId
    }
  }
  greWordsCount(where: $where)
}

mutation DeleteGreWord($deleteGreWordId: String!) {
  deleteGreWord(id: $deleteGreWordId) {
    id
  }
}

mutation DeleteGptPrompt($deleteGptPromptId: String!) {
  deleteGptPrompt(id: $deleteGptPromptId) {
    id
  }
}

mutation UpdateGptPrompt($id: String!, $editedResponse: String) {
  updateGptPrompt(id: $id, editedResponse: $editedResponse) {
    id
    editedResponse
  }
}
