fragment UserFields on User {
  id
  email
  meta {
    defaultGreWordSearchPromptInput
    showDefaultGreWordSearchPromptInputs
  }
}
mutation createUser($email: String!) {
  createUser(email: $email) {
    ...UserFields
  }
}

query usersForLoginPage($where: UserWhereInput) {
  users(where: $where) {
    ...UserFields
  }
}
