mutation createUser($email: String!) {
  createUser(email: $email) {
    id
    email
    meta
  }
}

query usersForLoginPage($where: UserWhereInput) {
  users(where: $where) {
    id
    email
    meta
  }
}
