fragment UserFields on User {
  id
  email
  meta {
    defaultGreWordSearchPromptInput
    showDefaultGreWordSearchPromptInputs
  }
}
mutation createUser($email: String!) {
  createUser(email: $email) {
    ...UserFields
  }
}

query User($where: UserWhereUniqueInput!) {
  user(where: $where) {
    ...UserFields
  }
}
