query sendSinglePrompt($input: String!) {
  sendSinglePrompt(input: $input)
}

mutation createGreWord(
  $spelling: String!
  $promptInput: String!
  $promptResponse: String!
  $userId: String!
  $greWordTagId: String
) {
  createGreWord(
    spelling: $spelling
    promptInput: $promptInput
    promptResponse: $promptResponse
    userId: $userId
    greWordTagId: $greWordTagId
  ) {
    id
    spelling
    greWordTagId
    gptPrompts {
      id
      input
      response
    }
  }
}

query GreConfiguration {
  greConfiguration {
    defaultGreWordSearchPromptInputs
  }
}

mutation CreateGreWordTag($name: String!, $userId: String!) {
  createGreWordTag(name: $name, userId: $userId) {
    id
    name
  }
}

mutation DeleteGreWordTag($name: String!) {
  deleteGreWordTag(name: $name) {
    id
    name
  }
}
