query sendSinglePrompt($input: String!) {
  sendSinglePrompt(input: $input)
}

mutation createGreWord(
  $spelling: String!
  $promptInput: String!
  $promptResponse: String!
  $userId: String!
) {
  createGreWord(
    spelling: $spelling
    promptInput: $promptInput
    promptResponse: $promptResponse
    userId: $userId
  ) {
    id
    spelling
    gptPrompts {
      id
      input
      response
    }
  }
}

query GreConfiguration {
  greConfiguration {
    defaultGreWordSearchPromptInputs
  }
}
