query greWordSearchPromptInputs($where: GreWordSearchPromptInputWhereInput) {
  greWordSearchPromptInputs(where: $where) {
    id
    text
    userId
  }
}

mutation createGreWordSearchPromptInput($text: String!, $userId: String!) {
  createGreWordSearchPromptInput(text: $text, userId: $userId) {
    id
    text
    userId
  }
}

mutation updateGreWordSearchPromptInput($text: String!, $id: String!) {
  updateGreWordSearchPromptInput(text: $text, id: $id) {
    id
    text
    userId
  }
}

mutation deleteGreWordSearchPromptInput($id: String!) {
  deleteGreWordSearchPromptInput(id: $id) {
    id
  }
}

# TODO: id, email, meta fields can be listed using Fragment
mutation updateMetaForUser(
  $id: String
  $email: String
  $meta: UserMetaParsedJsonValueInput
) {
  updateUser(id: $id, email: $email, meta: $meta) {
    ...UserFields
  }
}
