query greWordSearchPromptInputs($where: GreWordSearchPromptInputWhereInput) {
  greWordSearchPromptInputs(where: $where) {
    id
    text
    userId
  }
}

mutation createGreWordSearchPromptInput($text: String!, $userId: String!) {
  createGreWordSearchPromptInput(text: $text, userId: $userId) {
    id
    text
  }
}

mutation updateGreWordSearchPromptInput($text: String!, $id: String!) {
  updateGreWordSearchPromptInput(text: $text, id: $id) {
    id
    text
  }
}

mutation deleteGreWordSearchPromptInput($id: String!) {
  deleteGreWordSearchPromptInput(id: $id) {
    id
  }
}
